[package]
name = "Ven"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.1"
eframe = "0.31.1"
egui_extras = "0.31.1"
egui-miniquad = { git = 'https://github.com/not-fl3/egui-miniquad.git', branch="master" }
macroquad = { version="0.4.5", default-features=false }

rfd = "0.15.4"

[profile.dev.package."*"]
opt-level = 3
